config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "videos#index"

  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    ziggeo = Ziggeo.new(ENV["ZIGGEO_APP_TOKEN"], ENV["ZIGGEO_PRIVATE_KEY"], ENV["ZIGGEO_ENCRYPTION_KEY"])
    @videos = ziggeo.videos.index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ziggeor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//assets-cdn.ziggeo.com/v1-stable/ziggeo.css" />
    <script src="//assets-cdn.ziggeo.com/v1-stable/ziggeo.js"></script>
    <script>ZiggeoApi.token = "<%= ENV['ZIGGEO_APP_TOKEN'] %>";</script>
  </head>

  <body>
    <nav class="nav navbar-inverse">
      <div class="container" >
        <div class="navbar-header">
          <%= link_to "9K", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar">
          <% if defined?(current_user) %>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li class="navbar-text">Hello <%= current_user.email %></li>
                <li><%= link_to "Sign out", destroy_user_session_path %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end -%>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/videos/_video.html.erb
<div class="card">
  <div class="card-block">
    <ziggeo ziggeo-video='<%= video['token'] %>'
            ziggeo-width="320"
            ziggeo-height="240" ziggeo-popup>
    </ziggeo>
</div>

app/views/videos/index.html.erb
<h1>Videos</h1>
<%= link_to 'Add video', new_video_path %>
<%= render partial: 'video', collection: @videos, as: :video %>

app/views/videos/new.html.erb
<div class="container">
  <ziggeo ziggeo-limit="60" ziggeo-width="320" ziggeo-height="240"
    ziggeo-perms="allowupload" ziggeo-tags="<%= current_user.uid %>"></ziggeo>
</div>